In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("Student Mental Health Analysis During Online Learning.csv")
df

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,Male,15,Class 8,7.1,8.9,9.3,Medium,No,Same
1,Meera,Female,25,MSc,3.3,5.0,0.2,Medium,No,Same
2,Ishaan,Male,20,BTech,9.5,5.4,6.2,Medium,No,Same
3,Aditya,Male,20,BA,10.8,5.6,5.5,High,Yes,Same
4,Anika,Female,17,Class 11,2.8,5.4,3.1,Medium,Yes,Same
...,...,...,...,...,...,...,...,...,...,...
995,Diya,Female,26,MA,11.3,6.8,9.1,Medium,No,Same
996,Aarav,Male,20,BTech,5.5,6.7,6.8,Low,Yes,Same
997,Myra,Female,15,Class 9,7.1,4.1,1.9,Low,Yes,Declined
998,Myra,Female,20,BA,4.4,7.5,4.5,Medium,No,Improved
999,Vihaan,Male,23,MA,10.8,7.7,3.6,Low,No,Improved

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Name                          1000 non-null   str
 1   Gender                        1000 non-null   str
 2   Age                           1000 non-null   int64
 3   Education Level               1000 non-null   str
 4   Screen Time (hrs/day)         1000 non-null   float64
 5   Sleep Duration (hrs)          1000 non-null   float64
 6   Physical Activity (hrs/week)  1000 non-null   float64
 7   Stress Level                  1000 non-null   str
 8   Anxious Before Exams          1000 non-null   str
 9   Academic Performance Change   1000 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 106.3 KB

In [4]:
df.isnull().sum()

Name                            0
Gender                          0
Age                             0
Education Level                 0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
dtype: int64

In [5]:
stress_level_counts = df['Stress Level'].value_counts()
stress_level_counts

Stress Level
Medium    492
Low       327
High      181
Name: count, dtype: int64

In [6]:
fig = px.histogram(df, x='Stress Level', title='Distribution of Stress Levels', color = 'Stress Level')
fig.show()

In [7]:
num_cols = ['Age', 'Screen Time (hrs/day)', 'Sleep Duration (hrs)', 'Physical Activity (hrs/week)']

for col in num_cols:
    fig = px.box(df, x='Stress Level', y=col, color='Stress Level',
                 title=f'{col} vs Stress Level',
                 #category_orders={'Stress Level': ['Low', 'Medium', 'High']}
                 )
    fig.show()

In [8]:
cat_cols = ['Gender', 'Education Level', 'Anxious Before Exams', 'Academic Performance Change']

for col in cat_cols:
    fig = px.box(df, x=col, y='Screen Time (hrs/day)', color='Stress Level',
                 title=f'{col} vs Screen Time (colored by Stress Level)',
                 #category_orders={'Stress Level': ['Low', 'Medium', 'High']}
                 )
    fig.show()

In [9]:
df = df.drop(columns=['Name'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Gender                        1000 non-null   str
 1   Age                           1000 non-null   int64
 2   Education Level               1000 non-null   str
 3   Screen Time (hrs/day)         1000 non-null   float64
 4   Sleep Duration (hrs)          1000 non-null   float64
 5   Physical Activity (hrs/week)  1000 non-null   float64
 6   Stress Level                  1000 non-null   str
 7   Anxious Before Exams          1000 non-null   str
 8   Academic Performance Change   1000 non-null   str
dtypes: float64(3), int64(1), str(5)
memory usage: 93.4 KB

In [10]:
df.head()

,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Male,15,Class 8,7.1,8.9,9.3,Medium,No,Same
1,Female,25,MSc,3.3,5.0,0.2,Medium,No,Same
2,Male,20,BTech,9.5,5.4,6.2,Medium,No,Same
3,Male,20,BA,10.8,5.6,5.5,High,Yes,Same
4,Female,17,Class 11,2.8,5.4,3.1,Medium,Yes,Same

In [11]:
from sklearn.preprocessing import LabelEncoder
edu_order = ['Class 8', 'Class 9', 'Class 10', 'Class 11', 'Class 12', 'BA', 'BSc','BTech', 'MA', 'MSc', 'MTech']

le = LabelEncoder()
le.classes_ = np.array(edu_order)
df['Education Level'] = le.transform(df['Education Level'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Gender                        1000 non-null   str
 1   Age                           1000 non-null   int64
 2   Education Level               1000 non-null   int64
 3   Screen Time (hrs/day)         1000 non-null   float64
 4   Sleep Duration (hrs)          1000 non-null   float64
 5   Physical Activity (hrs/week)  1000 non-null   float64
 6   Stress Level                  1000 non-null   str
 7   Anxious Before Exams          1000 non-null   str
 8   Academic Performance Change   1000 non-null   str
dtypes: float64(3), int64(2), str(4)
memory usage: 88.6 KB

In [12]:
df.head()

,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Male,15,0,7.1,8.9,9.3,Medium,No,Same
1,Female,25,9,3.3,5.0,0.2,Medium,No,Same
2,Male,20,7,9.5,5.4,6.2,Medium,No,Same
3,Male,20,5,10.8,5.6,5.5,High,Yes,Same
4,Female,17,3,2.8,5.4,3.1,Medium,Yes,Same

In [13]:
stress_order = ['Low', 'Medium', 'High']
le2 = LabelEncoder()
le2.classes_ = np.array(stress_order)
df['Stress Level'] = le2.transform(df['Stress Level'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Gender                        1000 non-null   str
 1   Age                           1000 non-null   int64
 2   Education Level               1000 non-null   int64
 3   Screen Time (hrs/day)         1000 non-null   float64
 4   Sleep Duration (hrs)          1000 non-null   float64
 5   Physical Activity (hrs/week)  1000 non-null   float64
 6   Stress Level                  1000 non-null   int64
 7   Anxious Before Exams          1000 non-null   str
 8   Academic Performance Change   1000 non-null   str
dtypes: float64(3), int64(3), str(3)
memory usage: 84.0 KB

In [14]:
df.head()

,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Male,15,0,7.1,8.9,9.3,1,No,Same
1,Female,25,9,3.3,5.0,0.2,1,No,Same
2,Male,20,7,9.5,5.4,6.2,1,No,Same
3,Male,20,5,10.8,5.6,5.5,2,Yes,Same
4,Female,17,3,2.8,5.4,3.1,1,Yes,Same

In [15]:
df = pd.get_dummies(df, columns=['Gender', 'Anxious Before Exams', 'Academic Performance Change'])
df.head()

,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Gender_Female,Gender_Male,Gender_Other,Anxious Before Exams_No,Anxious Before Exams_Yes,Academic Performance Change_Declined,Academic Performance Change_Improved,Academic Performance Change_Same
0,15,0,7.1,8.9,9.3,1,False,True,False,True,False,False,False,True
1,25,9,3.3,5.0,0.2,1,True,False,False,True,False,False,False,True
2,20,7,9.5,5.4,6.2,1,False,True,False,True,False,False,False,True
3,20,5,10.8,5.6,5.5,2,False,True,False,False,True,False,False,True
4,17,3,2.8,5.4,3.1,1,True,False,False,False,True,False,False,True

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Age                                   1000 non-null   int64
 1   Education Level                       1000 non-null   int64
 2   Screen Time (hrs/day)                 1000 non-null   float64
 3   Sleep Duration (hrs)                  1000 non-null   float64
 4   Physical Activity (hrs/week)          1000 non-null   float64
 5   Stress Level                          1000 non-null   int64
 6   Gender_Female                         1000 non-null   bool
 7   Gender_Male                           1000 non-null   bool
 8   Gender_Other                          1000 non-null   bool
 9   Anxious Before Exams_No               1000 non-null   bool
 10  Anxious Before Exams_Yes              1000 non-null   bool
 11  Academic Performance Change_Declined  1000 non-null   bool
 12  Academic Performance Change_Improved  1000 non-null   bool
 13  Academic Performance Change_Same      1000 non-null   bool
dtypes: bool(8), float64(3), int64(3)
memory usage: 54.8 KB

In [17]:
from sklearn.model_selection import train_test_split

x = df.drop(columns=['Stress Level'])
y = df['Stress Level']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 13), (200, 13), (800,), (200,))

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [28]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train, y_train)

c:\Users\keert\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [29]:
lr = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
lr.fit(x_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [30]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42, class_weight='balanced')
dt.fit(x_train_scaled, y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [31]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42, class_weight = 'balanced')
rf.fit(x_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [32]:
y_pred_lr = lr.predict(x_test_scaled)
y_pred_dt = dt.predict(x_test_scaled)
y_pred_rf = rf.predict(x_test_scaled)

In [33]:
from sklearn.metrics import accuracy_score

acc_lr = accuracy_score(y_test, y_pred_lr)
acc_dt = accuracy_score(y_test, y_pred_dt)
acc_rf = accuracy_score(y_test, y_pred_rf)

In [34]:
acc_lr, acc_dt, acc_rf

(0.37, 0.385, 0.395)

In [35]:
from sklearn.metrics import classification_report
lr_report = classification_report(y_test, y_pred_lr)
dt_report = classification_report(y_test, y_pred_dt)
rf_report = classification_report(y_test, y_pred_rf)

In [36]:
lr_report, dt_report, rf_report

('              precision    recall  f1-score   support\n\n           0       0.36      0.40      0.38        68\n           1       0.59      0.37      0.45        98\n           2       0.17      0.32      0.22        34\n\n    accuracy                           0.37       200\n   macro avg       0.37      0.36      0.35       200\nweighted avg       0.44      0.37      0.39       200\n',
 '              precision    recall  f1-score   support\n\n           0       0.38      0.29      0.33        68\n           1       0.51      0.51      0.51        98\n           2       0.14      0.21      0.17        34\n\n    accuracy                           0.39       200\n   macro avg       0.34      0.34      0.34       200\nweighted avg       0.40      0.39      0.39       200\n',
 '              precision    recall  f1-score   support\n\n           0       0.34      0.25      0.29        68\n           1       0.45      0.62      0.52        98\n           2       0.07      0.03      0.04        34\n\n    accuracy                           0.40       200\n   macro avg       0.29      0.30      0.28       200\nweighted avg       0.35      0.40      0.36       200\n')

In [37]:
importance = pd.Series(rf.feature_importances_, index=x_train.columns)
importance = importance.sort_values(ascending=False)

figx = px.bar(importance, title='Feature Importance from Random Forest')
figx.show()

In [38]:
new_student = x_test.iloc[0]
y_test.iloc[0]
rf.predict([new_student])

array([1])